### ISSUE TITLE
URIs of Context should point to production

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/connector-accuweather#1]
There are different files where context URI have values according to ontotest environment. Examples:
- https://github.com/PlatformOfTrust/connector-accuweather/blob/master/config/config.go 
- https://github.com/PlatformOfTrust/connector-accuweather/blob/master/README.md 
- https://github.com/PlatformOfTrust/connector-accuweather/blob/master/schemas_request.go
- https://github.com/PlatformOfTrust/connector-accuweather/blob/master/schemas_response.go

**Wanted**
Since production ontology is released, it can be now used (eg https://standards.oftrust.net/v2/Context/DataProductContext/Forecast/Weather/AccuWeather/ )

**Comment by lime008** [comment]
94186de8
The default contexts have now been updated to the production ontology.
